.\" Please adjust this date whenever revising the manpage.
.TH HOWDY 1 "April 9, 2018" "Howdy help" "User Commands"
.SH NAME
howdy \- Windows Hello style authentication for Ubuntu
.SH DESCRIPTION
Howdy IR face recognition implements a PAM module to use your face as a authentication method.
.SS "Usage:"
.IP
howdy <command> [user] [argument]
.SS "Commands:"
.TP
help
Show this help page
.TP
list
List all saved face models for the current user
.TP
add
Add a new face model for the current user
.TP
remove
Remove a specific model
.TP
clear
Remove all face models for the current user
.TP
test
Test the camera and recognition methods
.PP
.SH AUTHOR
Howdy was written by boltgolt. For more information visit https://github.com/Boltgolt/howdy
